// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMJT9dx9H6BAwun45SbeyPR2iC4NSv4cY',
    appId: '1:488899564467:web:6af0b7d4a865d6118ef1c6',
    messagingSenderId: '488899564467',
    projectId: 'fltter-stud',
    authDomain: 'fltter-stud.firebaseapp.com',
    storageBucket: 'fltter-stud.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdLOd8_-kLxolbNVBZrET1dVUFVCBGfP0',
    appId: '1:488899564467:android:c940edd3ac07ff6c8ef1c6',
    messagingSenderId: '488899564467',
    projectId: 'fltter-stud',
    storageBucket: 'fltter-stud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzlOgCNlpcgonbjXFnjR1Fv4xHseSW6MQ',
    appId: '1:488899564467:ios:5d71520ba38a28488ef1c6',
    messagingSenderId: '488899564467',
    projectId: 'fltter-stud',
    storageBucket: 'fltter-stud.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzlOgCNlpcgonbjXFnjR1Fv4xHseSW6MQ',
    appId: '1:488899564467:ios:5d71520ba38a28488ef1c6',
    messagingSenderId: '488899564467',
    projectId: 'fltter-stud',
    storageBucket: 'fltter-stud.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMJT9dx9H6BAwun45SbeyPR2iC4NSv4cY',
    appId: '1:488899564467:web:9b60f31e38422ac78ef1c6',
    messagingSenderId: '488899564467',
    projectId: 'fltter-stud',
    authDomain: 'fltter-stud.firebaseapp.com',
    storageBucket: 'fltter-stud.firebasestorage.app',
  );
}
